services:
    postgres:
        image: "postgres:latest"
        environment:
            - "POSTGRES_DB=mydatabase"
            - "POSTGRES_PASSWORD=secret"
            - "POSTGRES_USER=myuser"
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    server:
        build: .
        ports:
            - "3001:3001"
        volumes:
            - .:/usr/src/app
        network_mode: "host"


volumes:
    postgres_data: